---
title: "Colombia validate credit model"
date: "2025-11-24"
output: 
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    highlight: tango
  bookdown::pdf_book:
    keep_tex: yes
---

<style type="text/css">
h1{
  font-size: 24pt;
}
h2{
  font-size: 18pt;
}
body{
  font-size: 12pt;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install packages

```{r load-packages, include=TRUE, eval=TRUE, message=FALSE, echo=TRUE, warning=FALSE, tidy=TRUE}
# Install and load packages
packages <- c(
    "data.table",
    "here",
    "purrr",
    "ggplot2",
    "ggsci",
    "hexbin",
    "bayesplot",
    "knitr",
    "kableExtra",
    "cmdstanr",
    "loo",
    "polycor",
    "GGally"
)
invisible(lapply(packages, library, character.only = TRUE))
```

```{r source-functions, include=TRUE, eval=TRUE, message=FALSE, echo=TRUE, warning=FALSE, tidy=TRUE}
source(here::here("R", "read_data_colombia.R"))
source(here::here("R", "train_test_split_data.R"))
source(here::here("R", "credit_model_run_analysis.R"))
```

# Data loading and pre-processing

```{r define-data-locations, include=TRUE, eval=TRUE, message=FALSE, echo=TRUE, warning=FALSE, tidy=TRUE}
dir_home <- "/Users/or105/Library/CloudStorage/OneDrive-ImperialCollegeLondon/OR_Work/2025/2025_project_Hope_Groups"
dir_data <- file.path(dir_home, "data")
dir_out <- file.path(dir_home, "colombia-validate-creditmodel-251125")
file_data <- file.path(dir_data, "Colombia_data_baseline_endline_itemised_250927.csv")
file_data_quasi <- file.path(dir_data, "Colombia_data_quasi_assignments_250927.csv")
output_file_prefix <- file.path(dir_out, "cm_1")
set.seed(42L)
```

```{r load-and-preprocess-data, include=TRUE, eval=TRUE, message=FALSE, echo=TRUE, warning=FALSE, tidy=TRUE}
# Read in data
tmp <- read_data_colombia(file_data)
dp <- copy(tmp$dp)
dit <- copy(tmp$dit)
dmeta <- copy(tmp$dmeta)
```

```{r load-and-preprocess-data, include=TRUE, eval=TRUE, message=FALSE, echo=TRUE, warning=FALSE, tidy=TRUE}
# Read in data
tmp <- read_data_colombia(file_data)
dp <- copy(tmp$dp)
dit <- copy(tmp$dit)
dmeta <- copy(tmp$dmeta)

dp1 <- subset(dp, !grepl("agg", item_label))
dp1[, time := time + 1L]
dp1[, y_stan := y + 1L]
tmp <- CJ(
    item_label = sort(unique(dp1$item_label)),
    time = unique(dp1$time)
)
tmp[, item_type := ifelse(
    grepl("CG-MH", item_label), "categorical", "out-of-7"
)]
tmp <- tmp[
    , list(
        item_label = item_label, time = time,
        item_time_id = seq_along(item_label)
    ),
    by = "item_type"
]
dp1 <- merge(dp1, tmp, by = c("item_label", "time"))
setkey(dp1, pid, time, item_label)
dp1[, oid := .I]
setkey(dp1, oid)
tmp <- dp1[, list(oid = oid, oidt = seq_along(y_stan)), by = "item_type"]
dp1 <- merge(dp1, tmp, by = c("item_type", "oid"))
setkey(dp1, pid, time, item_label)
```

```{r split-test-data, include=TRUE, eval=TRUE, message=FALSE, echo=TRUE, warning=FALSE, tidy=TRUE}
set.seed(42L)
test_individuals_p <- 0.5
test_items_p <- 0.5

tmp <- train_test_split_data(dp1, test_individuals_p, test_items_p)
dtest <- copy(tmp$test)
dtrain <- copy(tmp$train)

cat("\nNumber of observations", nrow(dp1))
cat("\nNumber of training observations", nrow(dtrain))
cat("\nNumber of test observations", nrow(dtest), " ", 100 * round(nrow(dtest) / nrow(dp1), d = 4), "%")
cat("\nSave test and training data split to file:", paste0(output_file_prefix, "_train_test_split.RData"), "\n")
save(dtrain, dtest, file = paste0(output_file_prefix, "_train_test_split.RData"))

# Remap PIDs on training data
tmp <- unique(subset(dtrain, select = c("pid")))
tmp[, pid_new := .I]
dtrain <- merge(dtrain, tmp, by = "pid")
setnames(
    dtrain,
    c("pid", "oid", "oidt", "pid_new"),
    c("pid_orig", "oid_orig", "oidt_orig", "pid")
)
dtrain[, oid := seq_len(nrow(dtrain))]
tmp <- dtrain[, list(oid = oid, oidt = seq_along(y_stan)), by = "item_type"]
dtrain <- merge(dtrain, tmp, by = c("item_type", "oid"))

# Remap PIDs on test data
tmp <- unique(subset(dtrain, select = c("pid", "pid_orig")))
setnames(tmp, c("pid", "pid_orig"), c("pid_new", "pid"))
dtest <- merge(dtest, tmp, by = "pid")
setnames(
    dtest,
    c("pid", "oid", "oidt", "pid_new"),
    c("pid_orig", "oid_orig", "oidt_orig", "pid")
)
dtest[, oid := .I]
tmp <- dtest[, list(oid = oid, oidt = seq_along(y_stan)), by = "item_type"]
dtest <- merge(dtest, tmp, by = c("item_type", "oid"))
```

```{r fit-on-training-data, include=TRUE, eval=TRUE, message=FALSE, echo=TRUE, warning=FALSE, tidy=TRUE}
cm_fit <- credit_model_run_analysis(
    dit,
    dtrain,
    output_file_prefix = paste0(output_file_prefix, "_trainingfit"),
    stan_file = here::here("src", "stan", "credit_model_2cats_v251120.stan"),
    chains = 2L,
    parallel_chains = 2L,
    iter_warmup = 500L,
    iter_sampling = 1500L,
    seed = 123L,
    with_core_analyses = FALSE,
    with_additional_analyses = FALSE
)
```

```{r evaluate-test-data, include=TRUE, eval=TRUE, message=FALSE, echo=TRUE, warning=FALSE, tidy=TRUE}
# Create stan_test_data following the same structure as training data
stan_test_data <- list()
stan_test_data$P <- 1L
stan_test_data$U <- max(dtrain$pid) # Use training data U, not test data
stan_test_data$Ncat1 <- nrow(dtest[item_type == "categorical", ])
stan_test_data$Qcat1 <- max(dtest[item_type == "categorical", item_time_id])
stan_test_data$Kcat1 <- length(unique(dtest[item_type == "categorical", y_stan]))
stan_test_data$cat1_y <- dtest[item_type == "categorical", y_stan]
stan_test_data$cat1_question_of_obs <- dtest[
    item_type == "categorical", item_time_id
]
stan_test_data$cat1_unit_of_obs <- dtest[item_type == "categorical", pid]
stan_test_data$cat1_X <- as.matrix(
    dtest[item_type == "categorical", time - 1L],
    ncol = 1
)
stan_test_data$Ncat2 <- nrow(dtest[item_type == "out-of-7", ])
stan_test_data$Qcat2 <- max(dtest[item_type == "out-of-7", item_time_id])
stan_test_data$Kcat2 <- length(unique(dtest[item_type == "out-of-7", y_stan]))
stan_test_data$cat2_y <- dtest[item_type == "out-of-7", y_stan]
stan_test_data$cat2_question_of_obs <- dtest[
    item_type == "out-of-7", item_time_id
]
stan_test_data$cat2_unit_of_obs <- dtest[item_type == "out-of-7", pid]
stan_test_data$cat2_X <- as.matrix(
    dtest[item_type == "out-of-7", time - 1L],
    ncol = 1
)

# Generate quantities for test data
cat("Running generate_quantities on test data...\n")
stan_file <- here::here("src", "stan", "credit_model_2cats_v251120.stan")
cm_compiled <- cmdstanr::cmdstan_model(
    stan_file,
    include_paths = dirname(stan_file)
)

# Extract draws and ensure latent_factor_unit sums to zero (fix numerical precision)
fitted_draws <- cm_fit$draws(format = "draws_matrix")
lfu_cols <- grep("^latent_factor_unit\\[", colnames(fitted_draws))
lfu_matrix <- fitted_draws[, lfu_cols]
row_means <- rowMeans(lfu_matrix)
fitted_draws[, lfu_cols] <- lfu_matrix - row_means
fitted_draws_array <- posterior::as_draws_array(fitted_draws)

cm_test_gq <- cm_compiled$generate_quantities(
    data = stan_test_data,
    fitted_params = fitted_draws_array,
    seed = 42L
)

saveRDS(
    cm_test_gq,
    file = paste0(output_file_prefix, "_test_generated_quantities.rds")
)

# Compute expected log predictive density (ELPD) per one test data point
log_lik_test <- cm_test_gq$draws("log_lik", format = "draws_matrix")
elpd_test <- mean(log(colMeans(exp(log_lik_test))))
cat("ELPD on test data:", elpd_test, "\n")

# Generate posterior predictive check on test data
po <- cm_test_gq$draws(
    variables = c("cat1_ypred", "cat2_ypred"),
    format = "draws_df"
)
po <- as.data.table(po)
po <- data.table::melt(
    po,
    id.vars = c(".draw", ".chain", ".iteration"),
    value.name = "ypred"
)
po[, item_type := gsub("([a-z0-9_]+)\\[([0-9]+)\\]", "\\1", variable)]
po[, oidt := as.integer(gsub("([a-z0-9_]+)\\[([0-9]+)\\]", "\\2", variable))]
set(po, po[, which(grepl("cat2", item_type))], "item_type", "out-of-7")
set(po, po[, which(grepl("cat1", item_type))], "item_type", "categorical")

pos <- po[,
    list(
        summary_value = quantile(
            ypred,
            prob = c(0.025, 0.25, 0.5, 0.75, 0.975)
        ),
        summary_name = c("q_lower", "iqr_lower", "median", "iqr_upper", "q_upper")
    ),
    by = c("item_type", "oidt")
]
pos <- data.table::dcast(pos,
    item_type + oidt ~ summary_name,
    value.var = "summary_value"
)

pos <- merge(pos, dtest, by = c("item_type", "oidt"))
pos[, IN_PPI := y_stan >= q_lower & y_stan <= q_upper]
cat("Proportion in 95% PPI (test data):", pos[, mean(IN_PPI)], "\n")

# Plot posterior predictive check for test data
p <- ggplot(pos, aes(x = oid, group = oid)) +
    geom_boxplot(
        aes(
            ymin = q_lower,
            lower = iqr_lower,
            middle = median,
            upper = iqr_upper,
            ymax = q_upper
        ),
        stat = "identity"
    ) +
    geom_point(aes(y = y_stan, colour = IN_PPI)) +
    facet_grid(item_label ~ time_label, scales = "free") +
    scale_x_discrete() +
    scale_y_continuous() +
    ggsci::scale_color_npg() +
    labs(
        x = "",
        y = "outcome",
        colour = "within\n95% posterior\nprediction\ninterval",
        title = "Posterior Predictive Check - Test Data"
    ) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
ggsave(
    file = paste0(output_file_prefix, "_test_ppcheck.png"),
    p,
    w = 20,
    h = 20
)
```
